# Site settings
name: Preston Liger
title: Preston Liger | Front End Software Engineer
description: front-end software engineer focused on building beautiful interfaces and experiences
url: https://pliger4.github.io/
baseurl: ''
email: pliger4@hotmail.com
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:pliger4@hotmail.com
  - title: github
    url: https://github.com/pliger4
  - title: linkedin
    url: https://www.linkedin.com/in/preston-liger-89517617b/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
